### ISSUE TITLE
How to determine the size of the textfield - don't use the frame modifier

### ISSUE THREAD

**Issue by dirkfabisch** [costachung/neumorphic#1]
Hi Costa,

thanks for the library. Currently I could not figure out how to determine the text field size, for the example for the search field. I try to avoid to give the Stack a fixed size. That will not work with Dynamic Text. 

![](https://user-images.githubusercontent.com/169746/77886613-c8a56000-729b-11ea-87d8-3742146645e6.png)

Any idea?

**Comment by costachung** [comment]
Hi @dirkfabisch, you do not need to determine the text field size. You can use the "background" method to add it under the text field. Like this:

`TextField("Search ...", text: $name).foregroundColor(Neumorphic.shared.secondaryColor())
                    .padding().background(
                    RoundedRectangle(cornerRadius: 30).fill(Neumorphic.shared.mainColor())
                    .softInnerShadow(RoundedRectangle(cornerRadius: 30), darkShadow: Neumorphic.shared.darkShadowColor(), lightShadow: Neumorphic.shared.lightShadowColor(), spread: 0.05, radius: 2)
                )`

Is that what you are looking for?

**Comment by dirkfabisch** [comment]
Perfect. That was exactly what I'm looking for!
<img width="464" alt="Screen Shot 2020-05-29 at 09 05 51" src="https://user-images.githubusercontent.com/5524851/83231374-b0629c00-a18b-11ea-9230-2d0c2a20c966.png">
