### ISSUE TITLE
Using .contextMenu deletes shadow when dismissing

### ISSUE THREAD

**Issue by LualdiD** [costachung/neumorphic#5]
Any idea on how to fix that not so great animation when closing a context menu on one of these views?

**Comment by costachung** [comment]
It looks like that the .contextMenu animation messed up with mask or clipShape. I am not sure if it is a bug on contextMenu.

Adding .contentShape fix the clipping problem.
https://stackoverflow.com/questions/62741902/contextmenu-on-a-rounded-lineargradient-produces-sharp-edges-in-swiftui

`            Button(action: {}) {
                Text("Tap me!")
            }.softButtonStyle(Capsule())
            .contentShape(Capsule())
            .contextMenu {
                Button(action: {}) {
                    Text("Option")
                    Image(systemName: "globe")
                }
            }
`

It's better but it's still not looking great.

**Comment by LualdiD** [comment]
Yeah, I'm doing that on my view already and with softOuterShadow it looks fine I open the contextMenu, but yes when I close it the shadow is gone for a second and then it jumps back in.
Trying to figure out a workaround for that but had no luck so far

**Comment by costachung** [comment]
I come up with a workaround which is adding a background view below the .contextMenu.

![ezgif-4-990c08150d7e](https://user-images.githubusercontent.com/169746/89745548-18682380-dae7-11ea-8dcf-b5df89ffed9b.gif)



```swift
            Button(action: {}) {
                Text("Button").fontWeight(.bold)
            }
            .softButtonStyle(Capsule(), pressedEffect: .none)
            .contentShape(Capsule())
            .contextMenu(
                ContextMenu(menuItems: {
                    Text("Menu Item 1")
                    Text("Menu Item 2")
                }
            ))
            .background(
                Capsule().fill(Neumorphic.shared.mainColor()).softOuterShadow()
            )
```




I 've release a new version v1.2.1 that you can change the pressed effect in soft button style. You can change the pressedEffect to .none so that the button won't show the inner shadow when it is pressed.

**Comment by LualdiD** [comment]
Nice I'm actually using on a view not a button but the workaround did the trick, I had to a background above and below the contextMenu but the animation is much better now 👍
