### ISSUE TITLE
Support for Toggle

### ISSUE THREAD

**Issue by TheMisfit68** [costachung/neumorphic#8]
Hi,

I love the project, but needed support for Toggle instead of a normal button (to make the button stick when pressed)
I created a SoftToggleStyle based on SoftButtonStyle (with only minor modifications).

`
extension Toggle {
    
    public func SoftToggleStyle<S : Shape>(_ content: S, padding : CGFloat = 16, mainColor : Color = Neumorphic.shared.mainColor(), textColor : Color = Neumorphic.shared.secondaryColor(), darkShadowColor: Color = Neumorphic.shared.darkShadowColor(), lightShadowColor: Color = Neumorphic.shared.lightShadowColor(), pressedEffect : SoftButtonPressedEffect = .hard) -> some View {
        self.toggleStyle(SoftDynamicToggleStyle(content, mainColor: mainColor, textColor: textColor, darkShadowColor: darkShadowColor, lightShadowColor: lightShadowColor, pressedEffect : pressedEffect, padding:padding))
    }
    
    public struct SoftDynamicToggleStyle<S: Shape> : ToggleStyle {
        
        var shape: S
        var mainColor : Color
        var textColor : Color
        var darkShadowColor : Color
        var lightShadowColor : Color
        var pressedEffect : SoftButtonPressedEffect
        var padding : CGFloat
        
        public init(_ shape: S, mainColor : Color, textColor : Color, darkShadowColor: Color, lightShadowColor: Color, pressedEffect : SoftButtonPressedEffect, padding : CGFloat = 16) {
            self.shape = shape
            self.mainColor = mainColor
            self.textColor = textColor
            self.darkShadowColor = darkShadowColor
            self.lightShadowColor = lightShadowColor
            self.pressedEffect = pressedEffect
            self.padding = padding
        }
        
        public func makeBody(configuration: Self.Configuration) -> some View {
            
            ZStack{
                
                ZStack{
                    if pressedEffect == .flat {
                        shape.stroke(darkShadowColor, lineWidth : configuration.isOn ? 1 : 0)
                            .opacity(configuration.isOn ? 1 : 0)
                        shape.fill(mainColor)
                    }
                    else if pressedEffect == .hard {
                        shape.fill(mainColor)
                            .softInnerShadow(shape, darkShadow: darkShadowColor, lightShadow: lightShadowColor, spread: 0.15, radius: 3)
                            .opacity(configuration.isOn ? 1 : 0)
                    }
                    
                    shape.fill(mainColor)
                        .softOuterShadow(darkShadow: darkShadowColor, lightShadow: lightShadowColor, offset: 6, radius: 3)
                        .opacity(pressedEffect == .none ? 1 : (configuration.isOn ? 0 : 1) )
                }
                
                configuration.label.foregroundColor(textColor)
                
            }
            .padding(padding)
            .scaleEffect(configuration.isOn ? 0.97 : 1)
        }
        
    }
    
}
`

**Comment by costachung** [comment]
I'm glad that you love the project. I like your idea to adding support for Toggle. It is great to expand this and support more SwiftUI components in the future. Let's work on Toggle first.

**Comment by costachung** [comment]
The code that you posted won't work on dynamic size. We can however borrow the code from "SoftDynamicButtonStyle" that use background modifier to get the correct size. I also added onTapGesture to toggle the button.

![Screen Shot 2020-12-11 at 12 10 48 PM](https://user-images.githubusercontent.com/169746/101860944-ef958f00-3ba9-11eb-9ba1-3847c26fbb02.png)

**Comment by costachung** [comment]
I would also like to add support for this neumorphic style toggle button below because it looks more like the iOS system toggle button.

![Screen Shot 2020-12-11 at 11 12 27 AM](https://user-images.githubusercontent.com/169746/101861597-5d8e8600-3bab-11eb-8980-ff0edf6e3a7b.png)

**Comment by costachung** [comment]
I 've pushed it to the master so that you can test it and see the "SoftToggleDemoView.swift" in the example project.

**Comment by TheMisfit68** [comment]
Hi,

Thanks for including SoftToggleStyle :-)
However the toggle I need has no text label just two small SFSymbols ("playfill" and "stopfill"), so the background takes on a minimum size and I can't seem to make it bigger (hence the code I posted).

Also with onTapgesture  already built in, how can I call some additional method each time the button gets toggled?

thnx

**Comment by costachung** [comment]
> Hi,
> 
> 
> 
> Thanks for including SoftToggleStyle :-)
> 
> However the toggle I need has no text label just two small SFSymbols ("playfill" and "stopfill"), so the background takes on a minimum size and I can't seem to make it bigger (hence the code I posted).
> 
> 
> 
> Also with onTapgesture  already built in, how can I call some additional method each time the button gets toggled?
> 
> 
> 
> thnx

If you want to do something whenever the toggle state change, you may use "didSet".

https://stackoverflow.com/questions/59395501/do-something-when-toggle-state-changes

Or use "onChange"
https://stackoverflow.com/questions/63287237/swiftui-call-function-when-toggle-is-tapped-and-the-state-of-the-variable-chang

**Comment by costachung** [comment]
Added a new softSwitchToggleStyle(). You can take a look in the SoftToggleDemoView in the example project.

![Screen Shot 2020-12-11 at 11 52 38 PM](https://user-images.githubusercontent.com/169746/101924993-4f248680-3c0c-11eb-9c5f-3dce3152bfba.png)

**Comment by costachung** [comment]
![Screen Shot 2020-12-12 at 4 16 16 PM](https://user-images.githubusercontent.com/169746/101979392-ce12d100-3c97-11eb-9d45-4e82cef6337b.png)

Released a new version 1.2.4 which add support for Toggle.

**Comment by TheMisfit68** [comment]
Tested on my own app. Works like charm :-D
Small issue left with dark mode, but might be my own code acting up.
